import type {
	CompanionInputFieldMultiDropdown,
	CompanionInputFieldNumber,
	CompanionInputFieldCheckbox,
	CompanionInputFieldDropdown,
	DropdownChoice,
} from '@companion-module/base'
import { MaskPropertiesPickers, AtemRatePicker } from './common.js'
import { WithDropdownPropertiesPicker } from './util.js'
import { Enums } from 'atem-connection'

export const CHOICES_CURRENTKEYFRAMES: DropdownChoice<
	Enums.IsAtKeyFrame.A | Enums.IsAtKeyFrame.B | Enums.IsAtKeyFrame.RunToInfinite
>[] = [
	{ id: Enums.IsAtKeyFrame.A, label: 'A' },
	{ id: Enums.IsAtKeyFrame.B, label: 'B' },
	{ id: Enums.IsAtKeyFrame.RunToInfinite, label: 'Full / Infinite' },
]

export const CHOICES_FLYDIRECTIONS: DropdownChoice<Enums.FlyKeyDirection>[] = [
	{ id: Enums.FlyKeyDirection.CentreOfKey, label: 'Centre of key' },
	{ id: Enums.FlyKeyDirection.TopLeft, label: 'Top left' },
	{ id: Enums.FlyKeyDirection.TopCentre, label: 'Top centre' },
	{ id: Enums.FlyKeyDirection.TopRight, label: 'Top right' },
	{ id: Enums.FlyKeyDirection.MiddleLeft, label: 'Middle left' },
	{ id: Enums.FlyKeyDirection.MiddleCentre, label: 'Middle centre' },
	{ id: Enums.FlyKeyDirection.MiddleRight, label: 'Middle right' },
	{ id: Enums.FlyKeyDirection.BottomLeft, label: 'Bottom left' },
	{ id: Enums.FlyKeyDirection.BottomCentre, label: 'Bottom centre' },
	{ id: Enums.FlyKeyDirection.BottomRight, label: 'Bottom right' },
]

export const CHOICES_BORDER_BEVEL: DropdownChoice[] = [
	{ id: 0, label: 'None' },
	{ id: 1, label: 'InOut' },
	{ id: 2, label: 'In' },
	{ id: 3, label: 'Out' },
]

export function AtemUSKDVEPropertiesPickers(): {
	properties: CompanionInputFieldMultiDropdown<'properties'>

	positionX: CompanionInputFieldNumber<'positionX'>
	positionY: CompanionInputFieldNumber<'positionY'>
	sizeX: CompanionInputFieldNumber<'sizeX'>
	sizeY: CompanionInputFieldNumber<'sizeY'>
	rotation: CompanionInputFieldNumber<'rotation'>
	maskEnabled: CompanionInputFieldCheckbox<'maskEnabled'>
	maskTop: CompanionInputFieldNumber<'maskTop'>
	maskBottom: CompanionInputFieldNumber<'maskBottom'>
	maskLeft: CompanionInputFieldNumber<'maskLeft'>
	maskRight: CompanionInputFieldNumber<'maskRight'>
	shadowEnabled: CompanionInputFieldCheckbox<'shadowEnabled'>
	lightSourceDirection: CompanionInputFieldNumber<'lightSourceDirection'>
	lightSourceAltitude: CompanionInputFieldNumber<'lightSourceAltitude'>
	borderEnabled: CompanionInputFieldCheckbox<'borderEnabled'>
	borderHue: CompanionInputFieldNumber<'borderHue'>
	borderSaturation: CompanionInputFieldNumber<'borderSaturation'>
	borderLuma: CompanionInputFieldNumber<'borderLuma'>
	borderBevel: CompanionInputFieldDropdown<'borderBevel'>
	borderOuterWidth: CompanionInputFieldNumber<'borderOuterWidth'>
	borderInnerWidth: CompanionInputFieldNumber<'borderInnerWidth'>
	borderOuterSoftness: CompanionInputFieldNumber<'borderOuterSoftness'>
	borderInnerSoftness: CompanionInputFieldNumber<'borderInnerSoftness'>
	borderOpacity: CompanionInputFieldNumber<'borderOpacity'>
	borderBevelPosition: CompanionInputFieldNumber<'borderBevelPosition'>
	borderBevelSoftness: CompanionInputFieldNumber<'borderBevelSoftness'>
	rate: CompanionInputFieldNumber<'rate'>
} {
	return WithDropdownPropertiesPicker({
		positionX: {
			type: 'number',
			label: 'Position: X',
			id: 'positionX',
			default: 0,
			min: -1000,
			range: true,
			step: 0.01,
			max: 1000,
			isVisibleExpression: `arrayIncludes($(options:properties), 'positionX')`,
			asInteger: false,
			clampValues: true,
		},
		positionY: {
			type: 'number',
			label: 'Position: Y',
			id: 'positionY',
			default: 0,
			range: true,
			min: -1000,
			step: 0.01,
			max: 1000,
			isVisibleExpression: `arrayIncludes($(options:properties), 'positionY')`,
			asInteger: false,
			clampValues: true,
		},
		sizeX: {
			type: 'number',
			label: 'Size: X',
			id: 'sizeX',
			default: 0.5,
			range: true,
			min: 0,
			step: 0.01,
			max: 99.99,
			isVisibleExpression: `arrayIncludes($(options:properties), 'sizeX')`,
			asInteger: false,
			clampValues: true,
		},
		sizeY: {
			type: 'number',
			label: 'Size: Y',
			id: 'sizeY',
			default: 0.5,
			range: true,
			min: 0,
			step: 0.01,
			max: 99.99,
			isVisibleExpression: `arrayIncludes($(options:properties), 'sizeY')`,
			asInteger: false,
			clampValues: true,
		},
		rotation: {
			type: 'number',
			label: 'Rotation',
			id: 'rotation',
			range: true,
			default: 0,
			min: 0,
			max: 360,
			isVisibleExpression: `arrayIncludes($(options:properties), 'rotation')`,
			asInteger: false,
			clampValues: true,
		},
		...MaskPropertiesPickers(52, 38, true),
		shadowEnabled: {
			type: 'checkbox',
			label: 'Shadow: Enabled',
			id: 'shadowEnabled',
			default: false,
			isVisibleExpression: `arrayIncludes($(options:properties), 'shadowEnabled')`,
		},
		lightSourceDirection: {
			type: 'number',
			label: 'Shadow: Angle',
			id: 'lightSourceDirection',
			default: 36,
			min: 0,
			range: true,
			step: 1,
			max: 359,
			isVisibleExpression: `arrayIncludes($(options:properties), 'lightSourceDirection')`,
			asInteger: false,
			clampValues: true,
		},
		lightSourceAltitude: {
			type: 'number',
			label: 'Shadow: Altitude',
			id: 'lightSourceAltitude',
			default: 25,
			min: 10,
			range: true,
			step: 1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'lightSourceAltitude')`,
			asInteger: false,
			clampValues: true,
		},
		borderEnabled: {
			type: 'checkbox',
			label: 'Border: Enabled',
			id: 'borderEnabled',
			default: true,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderEnabled')`,
		},
		borderHue: {
			type: 'number',
			label: 'Border: Hue',
			id: 'borderHue',
			default: 0,
			min: 0,
			range: true,
			step: 0.1,
			max: 360,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderHue')`,
			asInteger: false,
			clampValues: true,
		},
		borderSaturation: {
			type: 'number',
			label: 'Border: Sat',
			id: 'borderSaturation',
			default: 0,
			min: 0,
			range: true,
			step: 0.1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderSaturation')`,
			asInteger: false,
			clampValues: true,
		},
		borderLuma: {
			type: 'number',
			label: 'Border: Lum',
			id: 'borderLuma',
			default: 0,
			min: 0,
			range: true,
			step: 0.1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderLuma')`,
			asInteger: false,
			clampValues: true,
		},
		borderBevel: {
			type: 'dropdown',
			label: 'Border: Style',
			id: 'borderBevel',
			default: 0,
			choices: CHOICES_BORDER_BEVEL,
		},
		borderOuterWidth: {
			type: 'number',
			label: 'Border: Outer Width',
			id: 'borderOuterWidth',
			default: 0,
			min: 0,
			range: true,
			step: 0.01,
			max: 16,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderOuterWidth')`,
			asInteger: false,
			clampValues: true,
		},
		borderInnerWidth: {
			type: 'number',
			label: 'Border: Inner Width',
			id: 'borderInnerWidth',
			default: 0.2,
			min: 0,
			range: true,
			step: 0.01,
			max: 16,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderInnerWidth')`,
			asInteger: false,
			clampValues: true,
		},
		borderOuterSoftness: {
			type: 'number',
			label: 'Border: Outer Soften',
			id: 'borderOuterSoftness',
			default: 0,
			min: 0,
			range: true,
			step: 1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderOuterSoftness')`,
			asInteger: false,
			clampValues: true,
		},
		borderInnerSoftness: {
			type: 'number',
			label: 'Border: Inner Soften',
			id: 'borderInnerSoftness',
			default: 0,
			min: 0,
			range: true,
			step: 1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderInnerSoftness')`,
			asInteger: false,
			clampValues: true,
		},
		borderOpacity: {
			type: 'number',
			label: 'Border: Opacity',
			id: 'borderOpacity',
			default: 100,
			min: 0,
			range: true,
			step: 1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderOpacity')`,
			asInteger: true,
			clampValues: true,
		},
		borderBevelPosition: {
			type: 'number',
			label: 'Border: Bevel Position',
			id: 'borderBevelPosition',
			default: 0,
			min: 0,
			range: true,
			step: 1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderBevelPosition')`,
			asInteger: true,
			clampValues: true,
		},
		borderBevelSoftness: {
			type: 'number',
			label: 'Border: Bevel Soften',
			id: 'borderBevelSoftness',
			default: 0,
			min: 0,
			range: true,
			step: 1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderBevelSoftness')`,
			asInteger: true,
			clampValues: true,
		},
		rate: AtemRatePicker('Rate'),
	})
}
export function AtemUSKKeyframePropertiesPickers(): {
	properties: CompanionInputFieldMultiDropdown<'properties'>

	positionX: CompanionInputFieldNumber<'positionX'>
	positionY: CompanionInputFieldNumber<'positionY'>
	sizeX: CompanionInputFieldNumber<'sizeX'>
	sizeY: CompanionInputFieldNumber<'sizeY'>
	rotation: CompanionInputFieldNumber<'rotation'>
	maskTop: CompanionInputFieldNumber<'maskTop'>
	maskBottom: CompanionInputFieldNumber<'maskBottom'>
	maskLeft: CompanionInputFieldNumber<'maskLeft'>
	maskRight: CompanionInputFieldNumber<'maskRight'>
	lightSourceDirection: CompanionInputFieldNumber<'lightSourceDirection'>
	lightSourceAltitude: CompanionInputFieldNumber<'lightSourceAltitude'>
	borderHue: CompanionInputFieldNumber<'borderHue'>
	borderSaturation: CompanionInputFieldNumber<'borderSaturation'>
	borderLuma: CompanionInputFieldNumber<'borderLuma'>
	borderOuterWidth: CompanionInputFieldNumber<'borderOuterWidth'>
	borderInnerWidth: CompanionInputFieldNumber<'borderInnerWidth'>
	borderOuterSoftness: CompanionInputFieldNumber<'borderOuterSoftness'>
	borderInnerSoftness: CompanionInputFieldNumber<'borderInnerSoftness'>
	borderOpacity: CompanionInputFieldNumber<'borderOpacity'>
	borderBevelPosition: CompanionInputFieldNumber<'borderBevelPosition'>
	borderBevelSoftness: CompanionInputFieldNumber<'borderBevelSoftness'>
} {
	return WithDropdownPropertiesPicker({
		positionX: {
			type: 'number',
			label: 'Position: X',
			id: 'positionX',
			default: 0,
			min: -1000,
			range: true,
			step: 0.01,
			max: 1000,
			isVisibleExpression: `arrayIncludes($(options:properties), 'positionX')`,
			asInteger: false,
			clampValues: true,
		},
		positionY: {
			type: 'number',
			label: 'Position: Y',
			id: 'positionY',
			default: 0,
			range: true,
			min: -1000,
			step: 0.01,
			max: 1000,
			isVisibleExpression: `arrayIncludes($(options:properties), 'positionY')`,
			asInteger: false,
			clampValues: true,
		},
		sizeX: {
			type: 'number',
			label: 'Size: X',
			id: 'sizeX',
			default: 0.5,
			range: true,
			min: 0,
			step: 0.01,
			max: 99.99,
			isVisibleExpression: `arrayIncludes($(options:properties), 'sizeX')`,
			asInteger: false,
			clampValues: true,
		},
		sizeY: {
			type: 'number',
			label: 'Size: Y',
			id: 'sizeY',
			default: 0.5,
			range: true,
			min: 0,
			step: 0.01,
			max: 99.99,
			isVisibleExpression: `arrayIncludes($(options:properties), 'sizeY')`,
			asInteger: false,
			clampValues: true,
		},
		rotation: {
			type: 'number',
			label: 'Rotation',
			id: 'rotation',
			range: true,
			default: 0,
			min: 0,
			max: 360,
			isVisibleExpression: `arrayIncludes($(options:properties), 'rotation')`,
			asInteger: false,
			clampValues: true,
		},
		maskTop: {
			type: 'number',
			label: 'Mask: Top',
			id: 'maskTop',
			default: 0,
			range: true,
			min: 0,
			step: 0.01,
			max: 38,
			isVisibleExpression: `arrayIncludes($(options:properties), 'maskTop')`,
			asInteger: false,
			clampValues: true,
		},
		maskBottom: {
			type: 'number',
			label: 'Mask: Bottom',
			id: 'maskBottom',
			default: 0,
			range: true,
			min: 0,
			step: 0.01,
			max: 38,
			isVisibleExpression: `arrayIncludes($(options:properties), 'maskBottom')`,
			asInteger: false,
			clampValues: true,
		},
		maskLeft: {
			type: 'number',
			label: 'Mask: Left',
			id: 'maskLeft',
			default: 0,
			range: true,
			min: 0,
			step: 0.01,
			max: 52,
			isVisibleExpression: `arrayIncludes($(options:properties), 'maskLeft')`,
			asInteger: false,
			clampValues: true,
		},
		maskRight: {
			type: 'number',
			label: 'Mask: Right',
			id: 'maskRight',
			default: 0,
			range: true,
			min: 0,
			step: 0.01,
			max: 52,
			isVisibleExpression: `arrayIncludes($(options:properties), 'maskRight')`,
			asInteger: false,
			clampValues: true,
		},
		lightSourceDirection: {
			type: 'number',
			label: 'Shadow: Angle',
			id: 'lightSourceDirection',
			default: 36,
			min: 0,
			range: true,
			step: 1,
			max: 359,
			isVisibleExpression: `arrayIncludes($(options:properties), 'lightSourceDirection')`,
			asInteger: false,
			clampValues: true,
		},
		lightSourceAltitude: {
			type: 'number',
			label: 'Shadow: Altitude',
			id: 'lightSourceAltitude',
			default: 25,
			min: 10,
			range: true,
			step: 1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'lightSourceAltitude')`,
			asInteger: false,
			clampValues: true,
		},
		borderHue: {
			type: 'number',
			label: 'Border: Hue',
			id: 'borderHue',
			default: 0,
			min: 0,
			range: true,
			step: 0.1,
			max: 360,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderHue')`,
			asInteger: false,
			clampValues: true,
		},
		borderSaturation: {
			type: 'number',
			label: 'Border: Sat',
			id: 'borderSaturation',
			default: 0,
			min: 0,
			range: true,
			step: 0.1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderSaturation')`,
			asInteger: false,
			clampValues: true,
		},
		borderLuma: {
			type: 'number',
			label: 'Border: Lum',
			id: 'borderLuma',
			default: 0,
			min: 0,
			range: true,
			step: 0.1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderLuma')`,
			asInteger: false,
			clampValues: true,
		},
		borderOuterWidth: {
			type: 'number',
			label: 'Border: Outer Width',
			id: 'borderOuterWidth',
			default: 0,
			min: 0,
			range: true,
			step: 0.01,
			max: 16,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderOuterWidth')`,
			asInteger: false,
			clampValues: true,
		},
		borderInnerWidth: {
			type: 'number',
			label: 'Border: Inner Width',
			id: 'borderInnerWidth',
			default: 0.2,
			min: 0,
			range: true,
			step: 0.01,
			max: 16,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderInnerWidth')`,
			asInteger: false,
			clampValues: true,
		},
		borderOuterSoftness: {
			type: 'number',
			label: 'Border: Outer Soften',
			id: 'borderOuterSoftness',
			default: 0,
			min: 0,
			range: true,
			step: 1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderOuterSoftness')`,
			asInteger: false,
			clampValues: true,
		},
		borderInnerSoftness: {
			type: 'number',
			label: 'Border: Inner Soften',
			id: 'borderInnerSoftness',
			default: 0,
			min: 0,
			range: true,
			step: 1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderInnerSoftness')`,
			asInteger: false,
			clampValues: true,
		},
		borderOpacity: {
			type: 'number',
			label: 'Border: Opacity',
			id: 'borderOpacity',
			default: 100,
			min: 0,
			range: true,
			step: 1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderOpacity')`,
			asInteger: false,
			clampValues: true,
		},
		borderBevelPosition: {
			type: 'number',
			label: 'Border: Bevel Position',
			id: 'borderBevelPosition',
			default: 0,
			min: 0,
			range: true,
			step: 1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderBevelPosition')`,
			asInteger: false,
			clampValues: true,
		},
		borderBevelSoftness: {
			type: 'number',
			label: 'Border: Bevel Soften',
			id: 'borderBevelSoftness',
			default: 0,
			min: 0,
			range: true,
			step: 1,
			max: 100,
			isVisibleExpression: `arrayIncludes($(options:properties), 'borderBevelSoftness')`,
			asInteger: false,
			clampValues: true,
		},
	})
}
